import os
import Modules.eventAnalyzer as eventAnalyzer


def main(eventPath: str, docFile: str) -> None:
    """
    This is the event documentation generator.
    """
    
    if not eventPath.endswith("/"):
        eventPath += "/"

    os.system("./Scripts/eventPreAnalyzer.sh -r " + eventPath)

    if os.path.exists("./dataArrayEvent.txt"):
        source = eventPath + "TheliaEvents.php"
        eventAnalyzer.main(source, "parsedEvent2.md", docFile)

        os.remove("./dataArrayEvent.txt")
        print("./dataArrayEvent.txt removed.")
    else:
        print("Error: dataArrayEvent.txt not found. File generated by eventPreAnalyzer.sh script.")


if __name__ == "__main__":
    eventPath = input("Enter the path to the event directory: ")
    docFile = input("Enter the events documentation file to modify : ")
    main(eventPath, docFile)